update

diff --git a/driverctl b/driverctl
--- a/driverctl
+++ b/driverctl
@@ -1,10 +1,11 @@
-#!/bin/bash
+#!/usr/bin/bash
 
 confdir=/etc/driverctl.d
 bus=${SUBSYSTEM:-pci}
 probe=1
 save=1
 debug=0
+lockdir=/var/lock/driverctl
 
 declare -A devclasses
 devclasses=(["all"]=""
@@ -35,6 +36,7 @@ function debug()
 function error()
 {
     log "$@"
+    release_lock
     exit 1
 }
 
@@ -164,11 +166,34 @@ function list_persisted()
     done
 }
 
+function release_lock() {
+    flock -u 200 2>/dev/null || true
+}
+trap release_lock EXIT
+
 function set_override()
 {
+    # 全局锁
+    [ -d "$lockdir" ] || mkdir -p "$lockdir"
+    exec 200>"$lockdir/global.lock"
+    if ! flock -n 200 ; then
+        log "Device $dev is being operated by another driverctl instance, exiting."
+        exit 1
+    fi
+
     if [ ! -f "$syspath/driver_override" ]; then
         error "device does not support driver override: $dev"
     fi
+
+    local cur_drv=""
+    if [ -L "$syspath/driver" ]; then
+        cur_drv=$(basename "$(readlink "$syspath/driver")")
+        if [ -n "$drv" ] && [ "$cur_drv" == "$drv" ]; then
+            log "Device $dev is already bound to driver '$drv', skip override."
+            return 0
+        fi
+    fi
+
     if [ -n "$drv" ] && [ "$drv" != "none" ]; then
         debug "setting driver override for $dev: $drv"
         if [ ! -d "/sys/module/$drv" ]; then
@@ -178,10 +203,9 @@ function set_override()
     else
         debug "unsetting driver override for $dev"
     fi
+
     unbind
-    if [ "$drv" = "vfio-pci" ]; then
-      echo -n "$(< "$syspath/vendor") $(< "$syspath/device")" > "/sys/module/vfio_pci/drivers/pci:vfio-pci/new_id" 2>/dev/null
-    fi
+
     echo "$drv" > "$syspath/driver_override"
 
     if [ "$drv" != "none" ] && [ $probe -ne 0 ]; then
@@ -216,7 +240,6 @@ while (($# > 0)); do
             usage
             exit 1
         fi
-
         cmd=$1
         dev=$2
         drv=$3
@@ -227,7 +250,6 @@ while (($# > 0)); do
            usage
            exit 1
         fi
-
         cmd=$1
         dev=$2
         break
@@ -237,7 +259,6 @@ while (($# > 0)); do
            usage
            exit 1
         fi
-
         cmd=$1
         dev=$2
         break
@@ -247,7 +268,6 @@ while (($# > 0)); do
             usage
             exit 1
         fi
-
         if [ -n "$2" ] && [ ! "${devclasses[$2]+_}" ]; then
             error "device type must be one of: ${!devclasses[*]}"
         fi
@@ -260,7 +280,6 @@ while (($# > 0)); do
             usage
             exit 1
         fi
-
         cmd=$1
         break
         ;;
@@ -278,30 +297,21 @@ if [ -z "$cmd" ]; then
 fi
 
 if [ -n "$dev" ]; then
-    case ${dev} in
-    */*)
-        bus=${dev%%/*}
-        dev=${dev#*/}
-        ;;
-    esac
-    if [ -n "${DEVPATH:-}" ]; then
-        devpath="$DEVPATH"
-    else
-        devlink="/sys/bus/$bus/devices/$dev"
-        if [ "$cmd" == unset-override ]; then
-            devpath=${devlink}
+        case ${dev} in
+        */*)
+            bus=${dev%%/*}
+            dev=${dev#*/}
+            ;;
+        esac
+        if [ -n "${DEVPATH:-}" ]; then
+            devpath="$DEVPATH"
         else
-            if [ "$bus" = "pci" ] && [ ! -L "$devlink" ]; then
-                devlink="/sys/bus/$bus/devices/0000:$dev"
-                [ -L "$devlink" ] && dev="0000:$dev"
-            fi
+            devlink="/sys/bus/$bus/devices/$dev"
             [ -L "$devlink" ] || error "no such device: $dev"
-            devpath=$(realpath "$devlink")
+            devpath=$(realpath "$devlink" | cut -c5-)
         fi
-        devpath=${devpath:4}
-    fi
-    syspath="/sys/$devpath"
-    sddev="$bus-$dev"
+        syspath="/sys/$devpath"
+        sddev="$bus-$dev"
 fi
 
 case ${cmd} in
@@ -310,7 +320,7 @@ case ${cmd} in
             drv=$(< "$confdir/$sddev")
             set_override "$dev" "$drv"
         else
-            exit 1
+            error "not found $dev override"
         fi
         ;;
     get-driver)
@@ -328,16 +338,13 @@ case ${cmd} in
     set-override)
         set_override "$dev" "$drv"
         if [ $save -ne 0 ]; then
-            save_override
+           save_override
         fi
-
         ;;
     unset-override)
-        if [ -L "$syspath" ]; then
-            set_override "$dev" ""
-        fi
+        set_override "$dev" ""
         if [ $save -ne 0 ]; then
-            save_override
+           save_override
         fi
         ;;
 esac
